# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CsiCar
email: carsten.csiky@gmail.com
description: blog of csicar
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csicar.github.io" # the base hostname & protocol for your site
twitter_username: technikid
github_username:  csicar

# Build settings
markdown: kramdown
